/**
 * Version utility to get version dynamically from package.json
 */

import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Cache the version to avoid reading package.json repeatedly
let cachedVersion: string | null = null;

/**
 * Get the current version from package.json
 * @returns The version string from package.json
 */
export function getVersion(): string {
  if (cachedVersion) {
    return cachedVersion;
  }

  try {
    // Read package.json from the project root
    const packageJsonPath = join(__dirname, '../../package.json');
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
    const version = packageJson.version ?? '0.0.0';
    cachedVersion = version;
    return version;
  } catch {
    console.warn('Warning: Could not read version from package.json, using fallback');
    return '0.0.0';
  }
}

/**
 * Get the full package name with version
 * @returns The package name with version (e.g., "@dcversus/prp@0.4.9")
 */
export function getPackageVersion(): string {
  try {
    const packageJsonPath = join(__dirname, '../../package.json');
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
    const name = packageJson.name ?? '@dcversus/prp';
    const version = getVersion();
    return `${name}@${version}`;
  } catch {
    console.warn('Warning: Could not read package name from package.json, using fallback');
    return '@dcversus/prp@0.0.0';
  }
}

/**
 * Get the user agent string for HTTP requests
 * @returns A user agent string with the current version
 */
export function getUserAgent(service: string = 'prp-cli'): string {
  const version = getVersion();
  return `${service}/${version}`;
}

/**
 * Get the CLI user agent string
 * @returns The CLI user agent string
 */
export function getCliUserAgent(): string {
  return getUserAgent('prp-cli');
}

/**
 * Get the orchestrator user agent string
 * @returns The orchestrator user agent string
 */
export function getOrchestratorUserAgent(): string {
  return getUserAgent('@dcversus/prp-orchestrator');
}

/**
 * Generate a banner string with version info
 * @param template The template string to use
 * @returns The formatted banner with version
 */
export function getVersionBanner(template: string = 'Generated by PRP CLI v{version}'): string {
  const version = getVersion();
  return template.replace('{version}', version);
}

/**
 * Get a dependency version for templates
 * @returns The current version with ^ prefix for package.json dependencies
 */
export function getDependencyVersion(): string {
  const version = getVersion();
  return `^${version}`;
}